version: '3.8'

services:
  # 1. Veritabanı Servisimiz
  db:
    image: postgres:15-alpine
    container_name: postgre_testo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akagei -d testodb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: akagei
      POSTGRES_PASSWORD: akagei
      POSTGRES_DB: testodb
      LANG: en_US.utf8
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      

  # 2. Go Uygulamamız
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      # Veritabanına bağlanmak için gerekli bilgiler
      # Önemli: Host kısmına "localhost" değil, servis adı olan "db" yazıyoruz!
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: akagei
      DB_PASSWORD: akagei
      DB_NAME: testodb
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: